### PR TITLE
separate file based point store use from other output files

### PR DESCRIPTION
**Pull request by ahnitz**
This allows the file based point store to be used separately from the other output logging. We would like this functionality so that we can provide our own point store modified for use with our file formats without also requiring the extra output.

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
I don't see how this works. Logging should be controlled by setting a [logging](https://docs.python.org/3.5/howto/logging.html) consumer for the 'ultranest' module. If that is done before running UltraNest, it should be able to suppress all output.

If not writing to disk (log_dir not set), then self.log is true (if it is the main process), but self.log_to_disk is not. Is that case handled here?

**Comment by ahnitz** [comment]
The point is to separate the point store from other forms of writing to disk. By default this has no changes as you'll end up with the Nullstore which isn't fill backed. But if one replaces this we can fully use a file backed point store without other file output. In other words, it should be possible to checkpoint without the other output file products.

**Comment by JohannesBuchner** [comment]
I see, you are trying to prevent ultranest to create the "chains  extra  info  plots  results" folders and files therein. 
Why can you not delete all files aside from results/points.hdf5 after running ultranest?

**Comment by ahnitz** [comment]
@JohannesBuchner  It's possible for us to work around this from our side, but it does seem somewhat unnatural to tie an essential file (the actual saved progress) with other non-essential files (essentially debugging outputs). This patch should not have any effect on the produced output in the case log_to_disk is true or false in the default case. The only time this would differ is if log_to_disk were false, but something other than the NullPointStore were used. That's the case were would like to run it.

**Comment by JohannesBuchner** [comment]
I think we could add a `log_to_pointstore` attribute to the class, and set it to `log_to_disk` in `__init__`.

You can alter `log_to_disk` to `False` then before you call `run`.

**Comment by JohannesBuchner** [comment]
I wouldn't call the posterior chains and evidence summary debugging outputs though ;-)

**Comment by ahnitz** [comment]
@JohannesBuchner Ok, I'll update the PR as you suggest when I some free time.

**Pull request closed without merging**
