### PR TITLE
Update integrator.py

### PR DESCRIPTION
**Pull request by SmirnGreg**
Fix crashing when number of processes is larger than number of living points #43

### CODE REVIEW

**Comment by SmirnGreg** [comment]
Don't merge yet, I'll finish testing. But now it seems to work in production.

**Comment by SmirnGreg** [comment]
Seems that everything works fine for me.

**Comment by JohannesBuchner** [comment]
Please see here https://github.com/JohannesBuchner/UltraNest/issues/44#issuecomment-921706780

**Comment by JohannesBuchner** [comment]
Please remove the trailing space and let me know if the patch solves the crash.

**Comment by SmirnGreg** [comment]
For me, it solves the crash. Thanks again for the cooperation and fast suggestion on the fixes.

**Comment by JohannesBuchner** [comment]
Lets see if the CI is happy ... https://app.circleci.com/pipelines/github/JohannesBuchner/UltraNest/191/workflows/7ca08ede-01c8-4e80-9c68-0f5613988463/jobs/189

**Comment by JohannesBuchner** [comment]
Great, CI is happy, so I will make another release.

**Comment by JohannesBuchner** [comment]
3.3.3 is out!

Thanks a lot @SmirnGreg!

**Comment by JohannesBuchner** [comment]
Late but better than never: Thank you for your contribution! I added your name to the contributor list in the README.

**Pull request merged**
